[main]
font=Iosevka Nerd Font Propo:size=14
lines=15
width=50
prompt = "> "
dpi-aware = no
use-bold = false
inner-pad = 10
vertical-pad = 22
horizontal-pad = 24
minimal-lines = true

[colors]
# Gruvbox-material Dark color scheme
background=282828ff
text=d4be98ff
match=e78a4eff
selection=32302fff
selection-match=d8a657ff
selection-text=d4be98ff
border=32302fff

[border]
width=2
radius=0

[dmenu]
mode=text

[key-bindings]
delete-line-forward = none
next = Down Control+j
prev = Up Control+k
next-page = Page_Down Control+f
prev-page = Page_Up Control+b
cursor-left = Left
cursor-right = Right
